config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  # devise_for :users
  devise_for :users, path: 'user', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' } , :controllers  => {
             :registrations => 'my_devise/registrations',
            
           }
  

  get '/books/review' => 'books#review'
  resources :books 
   


  # get '/admin/:id', to: 'admin#edit', as: 'admin'
  resources :admin, only: [:edit ,:update]

  resources :home
  # devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_action :authenticate_user!
  def index
    @users = User.all 
      
   
  end

  def show
    @user = User.find(params[:id])
  end  

  def new 
   @user = User.new

  end
  

  def create
   user = User.new
   if user.save
      flash[:success] = "New User created." 

   else 
      render 'new'  
    end
     
  end


  def edit
     
     @user = User.find(params[:id])

  end
    

  def update
   
    @user = User.find(params[:id])
    if @user.update()
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity

    end
  end


  def destroy

   @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other

  end  




end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_form.html.erb
<%# if user_signed_in?%>


<%= form_with model: user do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :mobile_no %><br>
    <%= form.text_field :mobile_no %><br>
    
  </div>

    <div>
    <%= form.label :dob %><br>
    <%= form.date_field :dob %>
    
  </div>

      <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %>

  </div>

  


  <div>
    <%= form.submit %>
  </div>
<% end %>
<%# end %>

app/views/home/index.html.erb
 <%#if user_signed_in? && %>
<% if User.admin?(current_user) %>
   <div class="col-md-12 text-center">
   <%= link_to "book index", books_url,class:"btn btn-primary" %>
 </div>
    <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Hello, Admin
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Welcome to demo model.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  <h1 style="text-align: center" >Users</h1>


  
<div id="table-div">
  <table class="table table-hover" >
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Email</th>
      <th scope="col">Created at</th>
      <th scope="col">Updated at</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <% @users.each do |user| %>
      
             <tr scope="row">
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td>
          <div class="btn-group" aria-label="Basic mixed styles example">
          <%= link_to("Edit",edit_user_registration_path(user.id),class: "btn btn-success")%>
          <%= link_to "show",{:controller => 'home',:action => 'show',:id =>user.id},class: "btn btn-warning" %>
          <!-- edit_user_registration_path -->
           <% next if user.admin? %>
           <%= button_to 'delete',{:controller => 'home',:action => 'destroy',:id =>user.id},class: "btn btn-danger",:method => :delete %>
          </div>
        </td>
      </tr>


    <% end %>
  </table>
</div>

         <% else %>
          <% if user_signed_in? %>
           <div>
              <h1><%="Hello,#{current_user.name}"%></h1>
            <%= link_to "Enter Infomation", edit_user_registration_path ,class: "btn btn-primary mb-2"%><br>
                                    <!-- edit_admin_path(current_user.id)           -->
            <%= link_to "show user info","/home/#{current_user.id}" ,class: "btn btn-primary mb-2" %>  <br>                      
            <%= link_to "Enter New Book", {:controller => "books", :action => "new", :user_id => current_user.id },class: "btn btn-primary mb-2"  %><br>
               <%#= link_to "Enter New Book1", new_book_url(:id =>current_user.id) %>    
               <%= link_to "book index", books_url ,class: "btn btn-primary mb-2" %><br>
              
           </div>
             
              <% end %> 

                    <% end %>

app/views/home/show.html.erb
<div id="table-div">
  <table class="table table-hover">
    <thead>
 

    
    <tr>
      <th>Name</th>
      <td><%= @user.name %></td>
    </tr>

    <tr>
      <th>ID</th>
       <td><%= @user.id %></td> 
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @user.email %></td>  
    </tr>

    <tr>
      <th>Mobile</th>
      <td><%= @user.mobile_no %></td>  
    </tr>

    <tr>
      <th>Address</th>
      <td><%= @user.address %></td>  
    </tr>


    <tr>
      <th>Created at</th>
        <td><%= @user.created_at %></td>
    </tr>

    <tr>
      <th>Updated at</th>
      <td><%= @user.updated_at %></td>  
    </tr>

       <tr>
      <th>City</th>
      <td><%= City.admin(@user) %></td> 
      

    </tr>



    </thead>
  
  </table>
</div>
<div class="col-md-12 text-center">
 <%= link_to "Home", root_path,class: "btn btn-primary"  %>
</div>