config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  # devise_for :users
  devise_for :users, path: 'user', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' } , :controllers  => {
             :registrations => 'my_devise/registrations',
            
           }
  

  get '/books/review' => 'books#review'
  resources :books 
   


  # get '/admin/:id', to: 'admin#edit', as: 'admin'
  resources :admin, only: [:edit ,:update]

  resources :home
  # devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index

    @reviews = Review.all
  end

  def edit
 

  end

  def new
          @review = Review.new
          @book_id = params[:book_id]
          @book = Book.find(params[:book_id])
          session[:id] = @user.id   
  end

    def create
      @review = Review.new(review_params)
      if @book.save
        redirect_to @review
      else
        render :new,status: :unprocessable_entity
      end   
    end

  def show
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
<div class="card px-5 py-5">

<%= form_with model: book do |form| %>
  <div>
    <%= form.label :user_name %><br>
    <%= form.text_field :user_name %>
    <% book.errors.full_messages_for(:user_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.label :review %><br>
    <%= form.text_area :review %><br>
    <% book.errors.full_messages_for(:review).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
    
 

  <%#=form.hidden_field :user_id, input_html: { value: @user_id } %>
  <%# @id = session[:id] %>
   <%= form.hidden_field :book_id, value: session[:id] %>
  
  
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>
     </div>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form", review: @review %>

app/views/reviews/index.html.erb
<div id="table-div">
  <table class="table table-hover" >
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">User name</th>
      <th scope="col">Review</th>
    </tr>
    </thead>
      
    <% @reviews.each do |review| %>
           <% #binding.pry %>      

         <% current_user.admin? ? true : next if review.book_id != current_user.id %>

      <tr scope="row">
        <td><%= review.id %></td>
        <td><%= review.user_name %></td> 
       <td><%= review.review %></td>
        <td>
          <div class="btn-group" aria-label="Basic mixed styles example">
          <%= link_to("Edit",edit_review_path(review.id),class: "btn btn-success")%>
          <%= link_to "show","/reviews/#{review.id}",class: "btn btn-warning" %>
          

          <% next if !current_user.admin? %>
          
           <%= button_to 'delete',{:controller => 'reviews',:action => 'destroy',:id =>book.id},class: "btn btn-danger",:remote => true,:method => :delete %>
          </div>
        </td>
      </tr>
    <% end %>

  </table>
</div>

<div class="col-md-12 text-center">
  <%= link_to("User Home",root_path,class: "btn btn-outline-success") %>
</div>

app/views/reviews/new.html.erb
<h1 style="text-align :center;">New review</h1>

<%= render "form", review: @review %>

app/views/reviews/show.html.erb
<div id="table-div">
  <table class="table table-hover" >
    <thead>
    <tr> 
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
      
             <tr scope="row">
        <td><%= @review.user_name %></td>
        <td><%= @review.review %></td>
        <td>
          <%= link_to("Edit",edit_review_path(@review.id),class: "btn btn-success")%>

         
        </td>
      </tr>   
  </table>
</div>